services:
    next:
        build:
            context: .
            dockerfile: ./docker/next/Dockerfile
            platforms:
                - linux/amd64
        env_file:
            - .env
        restart: unless-stopped
        container_name: '${NEXT_CONTAINER_NAME:?err}'
        stdin_open: true
        tty: true
        ports:
            - '3000:3000'
        volumes:
            - .:/home/node/app
        depends_on:
            - postgres
            - mongo-rs0
            - mongo-rs1
            - minio
            - node

    postgres:
        image: postgres:17
        restart: unless-stopped
        container_name: '${POSTGRES_CONTAINER_NAME:?err}'
        ports:
            - '5432:5432'
        environment:
            POSTGRES_USER: '${POSTGRES_USER:?err}'
            POSTGRES_PASSWORD: '${POSTGRES_PASSWORD:?err}'
            POSTGRES_DB: '${POSTGRES_DB:?err}'
        volumes:
            - ./data/postgres:/var/lib/postgres/data

    mongo-rs0:
        build:
            context: .
            dockerfile: docker/mongo/mongo_rs0/Dockerfile
        restart: unless-stopped
        container_name: '${MONGO_CONTAINER_NAME:?err}-rs0'
        healthcheck:
            test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
            interval: 10s
            timeout: 10s
            retries: 5
        ports:
            - '27017:27017'
        environment:
            MONGO_INITDB_ROOT_USERNAME: '${MONGO_INITDB_ROOT_USERNAME:?err}'
            MONGO_INITDB_ROOT_PASSWORD: '${MONGO_INITDB_ROOT_PASSWORD:?err}'
            MONGO_INITDB_DATABASE: '${MONGO_INITDB_DATABASE:?err}'
            MONGO_INITDB_COLLECTION: '${MONGO_INITDB_COLLECTION:?err}'
            MONGO_HOST_RS0: '${MONGO_HOST_RS0:?err}'
            MONGO_PORT_RS0: '${MONGO_PORT_RS0:?err}'
            MONGO_HOST_RS1: '${MONGO_HOST_RS1:?err}'
            MONGO_PORT_RS1: '${MONGO_PORT_RS1:?err}'
        volumes:
            - ./rs_keyfile:/etc/mongodb/pki/keyfile
            - ./data/mongo-rs0:/data/db

    mongo-rs1:
        build:
            context: .
            dockerfile: docker/mongo/mongo_rs1/Dockerfile
        restart: unless-stopped
        container_name: '${MONGO_CONTAINER_NAME:?err}-rs1'
        ports:
            - '27018:27018'
        environment:
            MONGO_INITDB_ROOT_USERNAME: '${MONGO_INITDB_ROOT_USERNAME:?err}'
            MONGO_INITDB_ROOT_PASSWORD: '${MONGO_INITDB_ROOT_PASSWORD:?err}'
            MONGO_HOST_RS0: '${MONGO_HOST_RS0:?err}'
            MONGO_PORT_RS0: '${MONGO_PORT_RS0:?err}'
            MONGO_HOST_RS1: '${MONGO_HOST_RS1:?err}'
            MONGO_PORT_RS1: '${MONGO_PORT_RS1:?err}'
        volumes:
            - ./rs_keyfile:/etc/mongodb/pki/keyfile
            - ./data/mongo_rs1:/data/db
        depends_on:
            mongo-rs0:
                condition: service_healthy

    minio:
        container_name: '${MINIO_CONTAINER_NAME:?err}'
        image: minio/minio
        environment:
            MINIO_ACCESS_KEY: '${MINIO_ACCESS_KEY:?err}'
            MINIO_SECRET_KEY: '${MINIO_SECRET_KEY:?err}'
        command: server /data --console-address ":9001"
        ports:
            - '9000:9000'
            - '9001:9001'
        volumes:
            - ./data/minio:/data

    node:
        build:
            context: ${NODE_PROJECT_PATH:?err}
            dockerfile: ./docker/node/Dockerfile
            platforms:
                - linux/amd64
        env_file:
            - ${NODE_PROJECT_PATH:?err}/.env
        restart: unless-stopped
        container_name: '${NODE_CONTAINER_NAME:?err}'
        stdin_open: true
        tty: true
        ports:
            - '8000:8000'
        volumes:
            - ${NODE_PROJECT_PATH:?err}:/home/node/app
        depends_on:
            - postgres
            - mongo-rs0
            - mongo-rs1
            - minio
